Repository bcgov/design-system, pull requests merged in 2024-09, with the labels that each got.

#463 Add Checkbox and CheckboxGroup components
  packages/react-components/src/App.tsx
  packages/react-components/src/components/Checkbox/Checkbox.css
  packages/react-components/src/components/Checkbox/Checkbox.test.tsx
  packages/react-components/src/components/Checkbox/Checkbox.tsx
  packages/react-components/src/components/Checkbox/index.ts
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.css
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.test.tsx
  packages/react-components/src/components/CheckboxGroup/CheckboxGroup.tsx
  packages/react-components/src/components/CheckboxGroup/index.ts
  packages/react-components/src/components/Icons/SvgCheckIcon/SvgCheckIcon.tsx
  packages/react-components/src/components/Icons/SvgCheckIcon/index.ts
  packages/react-components/src/components/Icons/SvgDashIcon/SvgDashIcon.tsx
  packages/react-components/src/components/Icons/SvgDashIcon/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/CheckboxGroup/CheckboxGroup.tsx
  packages/react-components/src/pages/CheckboxGroup/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/Checkbox.stories.tsx
  packages/react-components/src/stories/CheckboxGroup.mdx
  packages/react-components/src/stories/CheckboxGroup.stories.tsx
Labels: enhancement

#482 Bump React component library deps
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#484 Add Vite build to React component library GHA test workflow
  .github/workflows/test_react_component_library.yaml
Labels: enhancement

#485 Checkbox index file exports CheckboxProps from React Aria Components
  packages/react-components/src/components/Checkbox/index.ts
Labels: bug

#483 Component cleanup
  packages/react-components/src/components/Form/Form.tsx
  packages/react-components/src/components/Form/index.ts
  packages/react-components/src/components/Icons/SvgTooltipArrowUp/SvgTooltipArrowUp.tsx
  packages/react-components/src/components/Icons/SvgTooltipArrowUp/index.ts
  packages/react-components/src/components/Switch/Switch.tsx
  packages/react-components/src/components/TextField/TextField.css
  packages/react-components/src/components/TextField/TextField.tsx
  packages/react-components/src/components/Tooltip/Tooltip.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/stories/Switch.stories.tsx
Labels: enhancement

#486 React components v0.2.2
  packages/react-components/CHANGELOG.md
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#472 Add Radio and RadioGroup components
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/App.tsx
  packages/react-components/src/components/Radio/Radio.css
  packages/react-components/src/components/Radio/Radio.test.tsx
  packages/react-components/src/components/Radio/Radio.tsx
  packages/react-components/src/components/Radio/index.ts
  packages/react-components/src/components/RadioGroup/RadioGroup.css
  packages/react-components/src/components/RadioGroup/RadioGroup.test.tsx
  packages/react-components/src/components/RadioGroup/RadioGroup.tsx
  packages/react-components/src/components/RadioGroup/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/RadioGroup/RadioGroup.tsx
  packages/react-components/src/pages/RadioGroup/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/RadioGroup.mdx
  packages/react-components/src/stories/RadioGroup.stories.tsx
Labels: enhancement

#487 Bump React component library dependencies
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#488 Switch animation obeys prefers-reduced-motion
  packages/react-components/src/components/Switch/Switch.css
Labels: enhancement

#489 Switch cursor styles apply to label for accessibility affordance
  packages/react-components/src/components/Switch/Switch.css
Labels: enhancement

#490 Add missing heading to Changelog for v0.2.3
  packages/react-components/CHANGELOG.md
Labels: content

#491 React components v0.3.0
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#492 Fix broken link in RadioGroup docs
  packages/react-components/src/stories/RadioGroup.mdx
Labels: bug, content

#481 Add Modal, Dialog and AlertDialog components
  packages/react-components/src/App.tsx
  packages/react-components/src/components/AlertDialog/AlertDialog.css
  packages/react-components/src/components/AlertDialog/AlertDialog.test.tsx
  packages/react-components/src/components/AlertDialog/AlertDialog.tsx
  packages/react-components/src/components/AlertDialog/index.ts
  packages/react-components/src/components/Dialog/Dialog.css
  packages/react-components/src/components/Dialog/Dialog.test.tsx
  packages/react-components/src/components/Dialog/Dialog.tsx
  packages/react-components/src/components/Dialog/index.ts
  packages/react-components/src/components/Modal/Modal.css
  packages/react-components/src/components/Modal/Modal.test.tsx
  packages/react-components/src/components/Modal/Modal.tsx
  packages/react-components/src/components/Modal/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/InlineAlert/InlineAlert.tsx
  packages/react-components/src/pages/ModalDialog/ModalDialog.tsx
  packages/react-components/src/pages/ModalDialog/index.ts
  packages/react-components/src/pages/TextField/TextField.tsx
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/AlertDialog.mdx
  packages/react-components/src/stories/AlertDialog.stories.tsx
  packages/react-components/src/stories/Dialog.stories.tsx
  packages/react-components/src/stories/Dialogs.mdx
  packages/react-components/src/stories/InlineAlert.mdx
  packages/react-components/src/stories/Modal.stories.tsx
Labels: enhancement

#493 Bump React component dependencies
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#494 React components v0.3.1
  packages/react-components/CHANGELOG.md
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#495 React components v0.4.0
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement
