Repository bcgov/design-system, pull requests merged in 2024-06, with the labels that each got.

#379 Replace deprecated @storybook/testing-library with current @storybook/test
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#383 Storybook a11y tests with Storybook Test Runner
  packages/react-components/.storybook/test-runner.ts
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#384 Make Button accessibility tests pass in Storybook
  packages/react-components/src/stories/Button.mdx
  packages/react-components/src/stories/Button.stories.tsx
Labels: content

#378 Update component documentation in Storybook
  packages/react-components/.storybook/preview.ts
  packages/react-components/src/components/Header/Header.tsx
  packages/react-components/src/stories/Button.mdx
  packages/react-components/src/stories/Footer.mdx
  packages/react-components/src/stories/Header.mdx
  packages/react-components/src/stories/Select.mdx
  packages/react-components/src/stories/Select.stories.tsx
  packages/react-components/src/stories/TagGroup.mdx
  packages/react-components/src/stories/TagGroup.stories.tsx
  packages/react-components/src/stories/Tooltip.mdx
Labels: content

#368 override automated test for aria-hidden-focus in Select component
  packages/react-components/src/stories/Select.stories.tsx
Labels: bug

#385 Add Playwright test run job to React component library test workflow
  .github/workflows/test_react_component_library.yaml
Labels: enhancement

#387 Set text input field inside container div for styling
  packages/react-components/src/components/TextField/TextField.css
  packages/react-components/src/components/TextField/TextField.tsx
  packages/react-components/src/stories/TextField.stories.tsx
Labels: enhancement
