Repository bcgov/design-system, pull requests merged in 2024-04, with the labels that each got.

#331 Tweaks to GitHub issue templates
  .github/ISSUE_TEMPLATE/1-component.yml
  .github/ISSUE_TEMPLATE/2-enhancement.yml
  .github/ISSUE_TEMPLATE/3-bug.yml
Labels: content

#328 Bump storybook to 8.0.6
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#338 bump storybook to 8.0.9
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#339 @bcgov/design-tokens v3.0.0-rc2
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/README.md
  packages/design-tokens/build-output.js
  packages/design-tokens/build/cjs-prefixed/index.d.ts
  packages/design-tokens/build/cjs-prefixed/index.js
  packages/design-tokens/build/cjs/index.d.ts
  packages/design-tokens/build/cjs/index.js
  packages/design-tokens/build/css-prefixed/variables.css
  packages/design-tokens/build/css/variables.css
  packages/design-tokens/build/js-prefixed/index.d.ts
  packages/design-tokens/build/js-prefixed/index.js
  packages/design-tokens/build/js/index.d.ts
  packages/design-tokens/build/js/index.js
  packages/design-tokens/dist/README.md
  packages/design-tokens/dist/cjs-prefixed/index.d.ts
  packages/design-tokens/dist/cjs-prefixed/index.js
  packages/design-tokens/dist/cjs/index.d.ts
  packages/design-tokens/dist/cjs/index.js
  packages/design-tokens/dist/css-prefixed/variables.css
  packages/design-tokens/dist/css/variables.css
  packages/design-tokens/dist/js-prefixed/index.d.ts
  packages/design-tokens/dist/js-prefixed/index.js
  packages/design-tokens/dist/js/index.d.ts
  packages/design-tokens/dist/js/index.js
  packages/design-tokens/dist/package.json
  packages/design-tokens/package-lock.json
  packages/design-tokens/package.json
Labels: enhancement
