Repository bcgov/design-system, pull requests merged in 2024-07, with the labels that each got.

#405 Add work in progress TextArea maxLength counter idea
  packages/react-components/src/components/TextArea/TextArea.tsx
  packages/react-components/src/pages/TextArea/TextArea.tsx
Labels: enhancement

#406 React components library v0.0.7
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#393 bump storybook version to 8.2.3
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#389 Add TextField component
  packages/react-components/src/App.tsx
  packages/react-components/src/components/TextField/TextField.css
  packages/react-components/src/components/TextField/TextField.tsx
  packages/react-components/src/components/TextField/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/TextField/TextField.tsx
  packages/react-components/src/pages/TextField/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/TextField.mdx
  packages/react-components/src/stories/TextField.stories.tsx
Labels: enhancement

#390 Select/dropdown - improve error handling and focus state
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/Select/Select.tsx
  packages/react-components/src/stories/Select.stories.tsx
Labels: bug

#392 Update button focus state to new design
  packages/react-components/src/components/Button/Button.css
Labels: enhancement

#396 Update tag focus and select states to new design
  packages/react-components/src/components/Tag/Tag.css
  packages/react-components/src/components/Tag/Tag.tsx
Labels: enhancement

#404 Fix Select button overflow issue
  packages/react-components/src/components/Select/Select.css
Labels: bug

#412 Text Field - remove unnecessary padding rule from label
  packages/react-components/src/components/TextField/TextField.css
Labels: bug

#411 bump storybook to 8.2.5
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#400 Add TextArea component
  packages/react-components/src/App.tsx
  packages/react-components/src/assets/icon-exclamation.svg
  packages/react-components/src/components/SvgExclamationIcon/SvgExclamationIcon.tsx
  packages/react-components/src/components/SvgExclamationIcon/index.ts
  packages/react-components/src/components/TextArea/TextArea.css
  packages/react-components/src/components/TextArea/TextArea.tsx
  packages/react-components/src/components/TextArea/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/TextArea/TextArea.tsx
  packages/react-components/src/pages/TextArea/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/TextArea.mdx
  packages/react-components/src/stories/TextArea.stories.tsx
Labels: enhancement

#413 Storybook - group TextField and TextArea together
  packages/react-components/src/stories/TextArea.stories.tsx
  packages/react-components/src/stories/TextField.stories.tsx
Labels: content

#415 React components library v0.0.9
  packages/react-components/CHANGELOG.md
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#414 Select - visible label when required rather than optional
  packages/react-components/src/components/Select/Select.tsx
  packages/react-components/src/stories/Select.mdx
Labels: enhancement

#409 Add Form component
  packages/react-components/src/components/Form/Form.tsx
  packages/react-components/src/components/Form/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/stories/Form.css
  packages/react-components/src/stories/Form.mdx
  packages/react-components/src/stories/Form.stories.tsx
Labels: enhancement

#416 Update label spacing on various components
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/TagGroup/TagGroup.css
  packages/react-components/src/components/TextArea/TextArea.css
  packages/react-components/src/components/TextArea/TextArea.tsx
  packages/react-components/src/components/TextField/TextField.css
Labels: bug

#420 React components library v0.0.10
  packages/react-components/CHANGELOG.md
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#419 0.1.0 release docs
  README.md
  packages/react-components/src/stories/Button.mdx
  packages/react-components/src/stories/Footer.mdx
  packages/react-components/src/stories/Header.mdx
  packages/react-components/src/stories/Introduction.mdx
  packages/react-components/src/stories/Select.mdx
  packages/react-components/src/stories/TagGroup.mdx
  packages/react-components/src/stories/TextArea.mdx
  packages/react-components/src/stories/TextField.mdx
  packages/react-components/src/stories/Tooltip.mdx
Labels: content

#421 Update README.md
  README.md
Labels: content

#422 React components library v0.1.0
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#423 Add GitHub release notes to README
  packages/react-components/README.md
Labels: content

#424 Add publish_react_component_library.yaml GitHub Actions workflow file
  .github/workflows/publish_react_component_library.yaml
Labels: enhancement

#425 Fix React components library npm publish workflow logic
  .github/workflows/publish_react_component_library.yaml
Labels: bug

#426 Add GitHub Actions info to React components README
  packages/react-components/README.md
Labels: content

#427 Add npm next tag info to README
  packages/react-components/README.md
Labels: content

#428 Update actions/checkout version in React components publish workflow
  .github/workflows/publish_react_component_library.yaml
  packages/react-components/README.md
Labels: enhancement

#432 Use React Aria Components v1.3.1
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#434 React components library v0.1.1
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement
