Repository bcgov/design-system, pull requests merged in 2024-05, with the labels that each got.

#335 Add deprecation notice to legacy 'about' page
  components/about/about.md
Labels: content

#337 update and clean up README.md
  README.md
Labels: content

#345 Fix hyperlink styling in Storybook
  packages/react-components/.storybook/main.ts
Labels: content

#346 remove bad styling from Storybook theme
  packages/react-components/.storybook/bcdsTheme.js
Labels: bug

#357 Use github.event.pull_request.head.sha instead of GITHUB_SHA workflow environment variable
  .github/workflows/build_react_component_library_apps.yaml
Labels: bug

#355 Select - change colour of "(optional)" label
  packages/react-components/src/components/Select/Select.css
Labels: bug

#362 Add missing typography-color-secondary to Select label
  packages/react-components/src/components/Select/Select.css
Labels: bug

#366 correct minimum required react version
  packages/react-components/README.md
Labels: content

#369 expanded introduction page for Storybook
  packages/react-components/.storybook/preview.ts
  packages/react-components/src/Changelog.mdx
  packages/react-components/src/stories/Introduction.mdx
Labels: content

#372 add changelog to dockerfile to fix broken storybook build
  packages/react-components/Dockerfile.storybook
Labels: bug

#373 bump storybook to 8.1.5
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies
