Repository bcgov/design-system, pull requests merged in 2024-08, with the labels that each got.

#429 TagGroup - add warning icon to error message
  packages/react-components/src/components/TagGroup/TagGroup.css
  packages/react-components/src/components/TagGroup/TagGroup.tsx
Labels: enhancement

#431 Select - expose description field
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/Select/Select.tsx
  packages/react-components/src/stories/Select.stories.tsx
Labels: enhancement

#437 Add inline alert component
  packages/react-components/src/App.tsx
  packages/react-components/src/components/Footer/Footer.tsx
  packages/react-components/src/components/Header/Header.tsx
  packages/react-components/src/components/Icons/SvgBcLogo/SvgBcLogo.tsx
  packages/react-components/src/components/Icons/SvgBcLogo/index.ts
  packages/react-components/src/components/Icons/SvgCheckCircleIcon/SvgCheckCircleIcon.tsx
  packages/react-components/src/components/Icons/SvgCheckCircleIcon/index.ts
  packages/react-components/src/components/Icons/SvgCloseIcon/SvgCloseIcon.tsx
  packages/react-components/src/components/Icons/SvgCloseIcon/index.ts
  packages/react-components/src/components/Icons/SvgExclamationCircleIcon/SvgExclamationCircleIcon.tsx
  packages/react-components/src/components/Icons/SvgExclamationCircleIcon/index.ts
  packages/react-components/src/components/Icons/SvgExclamationIcon/SvgExclamationIcon.tsx
  packages/react-components/src/components/Icons/SvgExclamationIcon/index.ts
  packages/react-components/src/components/Icons/SvgInfoIcon/SvgInfoIcon.tsx
  packages/react-components/src/components/Icons/SvgInfoIcon/index.ts
  packages/react-components/src/components/InlineAlert/InlineAlert.css
  packages/react-components/src/components/InlineAlert/InlineAlert.tsx
  packages/react-components/src/components/InlineAlert/index.ts
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/TagGroup/TagGroup.tsx
  packages/react-components/src/components/TextArea/TextArea.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/InlineAlert/InlineAlert.tsx
  packages/react-components/src/pages/InlineAlert/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/InlineAlert.mdx
  packages/react-components/src/stories/InlineAlert.stories.tsx
Labels: enhancement

#440 Add switch component
  packages/react-components/src/App.tsx
  packages/react-components/src/components/Switch/Switch.css
  packages/react-components/src/components/Switch/Switch.tsx
  packages/react-components/src/components/Switch/index.ts
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/Switch/Switch.tsx
  packages/react-components/src/pages/Switch/index.ts
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/Switch.mdx
  packages/react-components/src/stories/Switch.stories.tsx
Labels: enhancement

#446 Add ButtonGroup component and refactor Inline Alert
  packages/react-components/src/App.tsx
  packages/react-components/src/components/ButtonGroup/ButtonGroup.css
  packages/react-components/src/components/ButtonGroup/ButtonGroup.tsx
  packages/react-components/src/components/ButtonGroup/index.ts
  packages/react-components/src/components/InlineAlert/InlineAlert.css
  packages/react-components/src/components/InlineAlert/InlineAlert.tsx
  packages/react-components/src/components/index.ts
  packages/react-components/src/pages/ButtonGroup/ButtonGroup.tsx
  packages/react-components/src/pages/ButtonGroup/index.ts
  packages/react-components/src/pages/InlineAlert/InlineAlert.tsx
  packages/react-components/src/pages/index.ts
  packages/react-components/src/stories/ButtonGroup.mdx
  packages/react-components/src/stories/ButtonGroup.stories.tsx
  packages/react-components/src/stories/InlineAlert.mdx
  packages/react-components/src/stories/InlineAlert.stories.tsx
Labels: enhancement

#447 React components library v0.1.2
  packages/react-components/CHANGELOG.md
  packages/react-components/README.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#448 v0.1.3
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#449 InlineAlert close button is removed from document flow to center alert text vertically
  packages/react-components/src/components/InlineAlert/InlineAlert.css
  packages/react-components/src/components/InlineAlert/InlineAlert.tsx
Labels: discussion

#450 Select - refactor icons
  packages/react-components/src/components/Icons/SvgChevronDownIcon/SvgChevronDownIcon.tsx
  packages/react-components/src/components/Icons/SvgChevronDownIcon/index.ts
  packages/react-components/src/components/Icons/SvgChevronUpIcon/SvgChevronUpIcon.tsx
  packages/react-components/src/components/Icons/SvgChevronUpIcon/index.ts
  packages/react-components/src/components/InlineAlert/InlineAlert.tsx
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/Select/Select.tsx
  packages/react-components/src/components/index.ts
Labels: enhancement

#454 Test design tokens build
  .github/workflows/test_design_tokens_build.yaml
  packages/design-tokens/build-output.test.js
  packages/design-tokens/package-lock.json
  packages/design-tokens/package.json
Labels: enhancement, dependencies

#455 Design tokens test for expected output files
  packages/design-tokens/README.md
  packages/design-tokens/build-output.test.js
Labels: enhancement, dependencies

#457 Add GitHub Actions workflow to publish design tokens library to npm
  .github/workflows/publish_design_tokens.yaml
Labels: enhancement, dependencies

#456 Add test for theme.blue.100 token in design tokens build output
  packages/design-tokens/build-output.test.js
Labels: enhancement, dependencies

#458 Design tokens publish workflow targets package.json in dist directory
  .github/workflows/publish_design_tokens.yaml
Labels: enhancement, dependencies

#459 Update design tokens package scripts for CI
  packages/design-tokens/README.md
  packages/design-tokens/package.json
  packages/design-tokens/run-build.sh
  packages/design-tokens/run-prepare-npm-package.sh
  packages/design-tokens/run-publish-npm-package.sh
Labels: enhancement, dependencies

#460 Design tokens publish workflow uses access public flag
  .github/workflows/publish_design_tokens.yaml
Labels: enhancement, dependencies

#461 Re-arrange order of design tokens publish job so version is updated just prior to publishing
  .github/workflows/publish_design_tokens.yaml
Labels: enhancement, dependencies

#462 Add additional link to published package
  packages/design-tokens/README.md
Labels: enhancement, dependencies

#465 Design tokens v3.0.1
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/build-output.js
  packages/design-tokens/build/cjs-prefixed/index.d.ts
  packages/design-tokens/build/cjs-prefixed/index.js
  packages/design-tokens/build/cjs/index.d.ts
  packages/design-tokens/build/cjs/index.js
  packages/design-tokens/build/css-prefixed/variables.css
  packages/design-tokens/build/css/variables.css
  packages/design-tokens/build/js-prefixed/index.d.ts
  packages/design-tokens/build/js-prefixed/index.js
  packages/design-tokens/build/js/index.d.ts
  packages/design-tokens/build/js/index.js
  packages/design-tokens/dist/cjs-prefixed/index.d.ts
  packages/design-tokens/dist/cjs-prefixed/index.js
  packages/design-tokens/dist/cjs/index.d.ts
  packages/design-tokens/dist/cjs/index.js
  packages/design-tokens/dist/css-prefixed/variables.css
  packages/design-tokens/dist/css/variables.css
  packages/design-tokens/dist/js-prefixed/index.d.ts
  packages/design-tokens/dist/js-prefixed/index.js
  packages/design-tokens/dist/js/index.d.ts
  packages/design-tokens/dist/js/index.js
  packages/design-tokens/dist/package.json
  packages/design-tokens/package-lock.json
  packages/design-tokens/package.json
Labels: enhancement, dependencies

#466 Design tokens v3.1.0
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/build/cjs-prefixed/index.d.ts
  packages/design-tokens/build/cjs-prefixed/index.js
  packages/design-tokens/build/cjs/index.d.ts
  packages/design-tokens/build/cjs/index.js
  packages/design-tokens/build/css-prefixed/variables.css
  packages/design-tokens/build/css/variables.css
  packages/design-tokens/build/js-prefixed/index.d.ts
  packages/design-tokens/build/js-prefixed/index.js
  packages/design-tokens/build/js/index.d.ts
  packages/design-tokens/build/js/index.js
  packages/design-tokens/dist/cjs-prefixed/index.d.ts
  packages/design-tokens/dist/cjs-prefixed/index.js
  packages/design-tokens/dist/cjs/index.d.ts
  packages/design-tokens/dist/cjs/index.js
  packages/design-tokens/dist/css-prefixed/variables.css
  packages/design-tokens/dist/css/variables.css
  packages/design-tokens/dist/js-prefixed/index.d.ts
  packages/design-tokens/dist/js-prefixed/index.js
  packages/design-tokens/dist/js/index.d.ts
  packages/design-tokens/dist/js/index.js
  packages/design-tokens/dist/package.json
  packages/design-tokens/input/tokens.json
  packages/design-tokens/package-lock.json
  packages/design-tokens/package.json
Labels: enhancement, dependencies

#467 Bump storybook to 8.2.9
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#468 Bump React component library dependencies
  .github/workflows/test_react_component_library.yaml
  packages/react-components/package-lock.json
  packages/react-components/package.json
  packages/react-components/src/components/Button/Button.test.tsx
  packages/react-components/src/components/ButtonGroup/ButtonGroup.test.tsx
  packages/react-components/src/components/Form/Form.tsx
Labels: dependencies

#470 Design tokens v3.1.1
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/build/cjs-prefixed/index.js
  packages/design-tokens/build/cjs/index.js
  packages/design-tokens/build/css-prefixed/variables.css
  packages/design-tokens/build/css/variables.css
  packages/design-tokens/build/js-prefixed/index.js
  packages/design-tokens/build/js/index.js
  packages/design-tokens/dist/cjs-prefixed/index.js
  packages/design-tokens/dist/cjs/index.js
  packages/design-tokens/dist/css-prefixed/variables.css
  packages/design-tokens/dist/css/variables.css
  packages/design-tokens/dist/js-prefixed/index.js
  packages/design-tokens/dist/js/index.js
  packages/design-tokens/dist/package.json
  packages/design-tokens/input/tokens.json
  packages/design-tokens/package-lock.json
  packages/design-tokens/package.json
Labels: bug, dependencies

#471 Bump @bcgov/design-tokens to v3.1.1
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#469 Update components to use 3.1.0 tokens
  packages/react-components/src/components/Header/Header.css
  packages/react-components/src/components/Select/Select.css
  packages/react-components/src/components/Switch/Switch.css
  packages/react-components/src/components/Tag/Tag.css
  packages/react-components/src/components/TextArea/TextArea.css
  packages/react-components/src/components/TextField/TextField.css
  packages/react-components/src/stories/Button.mdx
  packages/react-components/src/stories/Footer.mdx
  packages/react-components/src/stories/Header.mdx
  packages/react-components/src/stories/InlineAlert.mdx
  packages/react-components/src/stories/TagGroup.mdx
  packages/react-components/src/stories/TextArea.mdx
  packages/react-components/src/stories/Tooltip.mdx
Labels: enhancement

#474 React components v0.1.4
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement, dependencies

#475 Change button style in inline alert example
  packages/react-components/src/stories/InlineAlert.stories.tsx
Labels: enhancement

#476 Unit tests for Header, Footer, Form, InlineAlert, Switch
  packages/react-components/src/components/Footer/Footer.test.tsx
  packages/react-components/src/components/Footer/Footer.tsx
  packages/react-components/src/components/Form/Form.test.tsx
  packages/react-components/src/components/Header/Header.test.tsx
  packages/react-components/src/components/Header/Header.tsx
  packages/react-components/src/components/InlineAlert/InlineAlert.test.tsx
  packages/react-components/src/components/InlineAlert/InlineAlert.tsx
  packages/react-components/src/components/Select/Select.tsx
  packages/react-components/src/components/Switch/Switch.test.tsx
Labels: enhancement

#477 React components v0.2.0
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#478 React components v0.2.1
  packages/react-components/CHANGELOG.md
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement
