Repository bcgov/design-system, pull requests merged in 2024-03, with the labels that each got.

#293 Bugfix: Provide Storybook build step with Vite config in Dockerfile
  packages/react-components/.storybook/main.ts
  packages/react-components/Dockerfile.storybook
Labels: bug

#297 Default footer content revisions
  packages/react-components/src/components/Footer/Footer.tsx
Labels: content

#299 Update Storybook branding
  packages/react-components/.storybook/bcdsTheme.js
  packages/react-components/.storybook/manager.js
Labels: content

#300 Fix logo in Storybook deployment
  packages/react-components/.storybook/bcdsTheme.js
  packages/react-components/.storybook/main.ts
  packages/react-components/Dockerfile.storybook
  packages/react-components/storybook-public/BCID_H_rgb_pos.svg
Labels: enhancement

#305 Add accessibility plugin to Storybook and update Storybook to 8.0.1
  packages/react-components/.storybook/main.ts
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: enhancement

#311 Refactor Storybook theme to use 3.0.0-rc1 tokens
  packages/react-components/.storybook/bcdsTheme.js
  packages/react-components/.storybook/manager.js
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#314 bump storybook to 8.0.4
  packages/react-components/package-lock.json
  packages/react-components/package.json
Labels: dependencies

#317 Update Button component to use v3 design tokens
  packages/react-components/src/components/Button/Button.css
Labels: dependencies
